Somehow forcing the compiler in through a different mechanism stopped the linker issue when attempting to determine the compiler ABI due to the fact that there is no stdlib available (so the compiler ABI check fails due to an undefined reference to _exit()).